name: stable

on: 
  push:
    branches:
      - 'stable'
    tags-ignore: 
      - '*'
jobs:
    test:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-pip
      steps:        
        - name: work around permission issue
          run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
        - uses: actions/checkout@v3
          with:
            fetch-depth: "0"
            submodules: recursive
        - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        - name: Build 
          run: pip3 install .
        - name: Generate Docs
          working-directory: ./docs
          run: make html
#        - name: Tests
#          run: make test
#        - name: Build Sphinx
#          run: rm -rf build && make clean-all && make html
#        - name: Report Coveralls
#          uses: AndreMiras/coveralls-python-action@develop
#        - name: Report Codacy
#          uses: codacy/codacy-coverage-reporter-action@v1
#          with:
#            project-token: ${{ secrets.CODACY_API_TOKEN }}
#            # or
#            #api-token: ${{ secrets.CODACY_API_TOKEN }}
#            coverage-reports: coverage.xml
